Don't use cd in setup/path.sh
cms-gem-daq-project/vfatqc-python-scripts pull request #110
Opened 2017-08-09 09:07 UTC by lmoureaux

Addresses bug #109 assuming that $BUILD_HOME is an absolute path.

2017-08-09 09:54 UTC, cbravo135 commented on setup/paths.sh
> +export "GEM_VFATQC_PROJECT=$BUILD_HOME/vfatqc-python-scripts"
Isn't it cleaner to do GEM_VFATQC_PROJECT first and then use it to make the others. This all could be done in 3 simpler lines.

2017-08-09 09:56 UTC, jsturdy requested changes

2017-08-09 09:56 UTC, jsturdy commented on setup/paths.sh
> +export "GEM_VFATQC_PROJECT=$BUILD_HOME/vfatqc-python-scripts"
Yeah, probably.
Also what is `GEM_VFATQC_PROJECT` actually used for?

2017-08-09 11:37 UTC, bdorney commented on setup/paths.sh
> +#export "PYTHONPATH=$PYTHONPATH:$BUILD_HOME/cmsgemos/gempython/tools"
shouldn't this be uncommented?

2017-08-09 11:40 UTC, bdorney requested changes
Agree w/@cbravo135 regarding cleaning up setup scripts.  Probably the same could be done in gem-plotting-tools

2017-08-09 12:22 UTC, lmoureaux commented on setup/paths.sh
> +export "GEM_VFATQC_PROJECT=$BUILD_HOME/vfatqc-python-scripts"
I didn't find any use of `GEM_VFATQC_PROJECT` in `vfatqc_python_tools`, `cmsgemos` and `gem-plotting-tools`

2017-08-09 12:22 UTC, lmoureaux commented on setup/paths.sh
> +#export "PYTHONPATH=$PYTHONPATH:$BUILD_HOME/cmsgemos/gempython/tools"
I didn't want to introduce any breaking change.

2017-08-09 14:52 UTC, jsturdy commented on setup/paths.sh
> +#export "PYTHONPATH=$PYTHONPATH:$BUILD_HOME/cmsgemos/gempython/tools"
* it was commented in the previous version (according to the diff in this PR)
* also no, the setup script in `cmsgemos` should appropriately set the `PYTHONPATH` for use, if it doesn't (it [does)](https://github.com/cms-gem-daq-project/cmsgemos/blob/generic-amc-release-v3/setup/paths.sh#L67) then open an issue there

2017-08-09 14:57 UTC, jsturdy commented on setup/paths.sh
> +export "GEM_VFATQC_PROJECT=$BUILD_HOME/vfatqc-python-scripts"
In that case, then you can make it a script local variable (if even at all), i.e., don't `export` it

2017-08-09 15:27 UTC, bdorney approved these changes

2017-08-11 16:07 UTC, jsturdy requested changes
* Prefer sandboxing of all setup scripts
 * Change  https://github.com/lmoureaux/vfatqc-python-scripts/blob/d97e2a0ae35ad541e2d48730271bcd24a2a90fe5/setup/paths.sh#L22-L29 to instruct the user to ensure that `
$BUILD_HOME/cmsgemos/setup/paths.sh` gets sourced
 * Same for https://github.com/lmoureaux/vfatqc-python-scripts/blob/d97e2a0ae35ad541e2d48730271bcd24a2a90fe5/setup/paths.sh#L31-L38
* Don't arbitrarily add locations to the `$PATH`, this will have negative consequences

2017-08-11 16:07 UTC, jsturdy commented on setup/paths.sh
> +export "PATH=$PATH:$BUILD_HOME/vfatqc-python-scripts/setup"
Line 44 should be removed unless there is a good reason to keep it

2017-08-11 16:07 UTC, jsturdy commented on setup/paths.sh
>  echo GEM_VFATQC_PROJECT $GEM_VFATQC_PROJECT
As per comments, if `GEM_VFATQC_PROJECT` isn't used outside this script, don't `export` it and remove line 48

2017-08-11 16:07 UTC, jsturdy commented on setup/paths.sh
> +#export "PYTHONPATH=$PYTHONPATH:$BUILD_HOME/cmsgemos/gempython/tools"
As is, just remove line 41

2017-08-11 16:31 UTC, jsturdy approved these changes

2017-08-11 16:32 UTC, jsturdy approved these changes
Closes #109

2017-08-11 16:32 UTC, merged