adding chan argument to ultraLatency.py
cms-gem-daq-project/vfatqc-python-scripts pull request #195
Opened 2018-07-19 13:36 UTC by brentstone

I have added a --chan argument to ultraLatency.py that allows the user to specify any single channel over which to run a latency scan on the VFATs. Previously, by default ultraLatency.py always conducted the scan over Channel 0.

## Description

I have added an argument "--chan" in the options parser to allow a channel to be specified for the scan. The default value of this argument is 0, as it was before. Then, in a conditional statement that asks if options.internal == True, I have passed options.chan to the variable scanChan instead of the value 0. This is on Line 174.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

In particular, some of the VFATs on the Integration stand have dead Channel 0 and so do not respond to the latency scan. This added functionality allows us to perform the latency scan over good channels in the VFATs in the event that Channel 0 (the previous default) is dead.

## How Has This Been Tested?

After implementing this change, I performed a latency scan with positive results. On the current integration stand setup, I have run the command "ultraLatency.py -c eagle64 -g0 --L1Atime=250 --mspl=3 --pulseDelay=40 --voltageStepPulse --internal --stepSize=1 --shelf=1 --scanmin=1 --scanmax=250 --chan=10" and can see during the course of the scan that values are written to registers corresponding to CHANNEL10 for all VFATs. In particular, VFAT 19 has a dead channel 0 but good channels otherwise (for the most part). If the latency scan is performed with the default CHANNEL0, then the scan result for VFAT 19 looks like the first screenshot below. When the channel is specified as --chan=10, then the result for VFAT 19 is the second screenshot below, showing a response.

### Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/26880226/42945768-804e396e-8b69-11e8-9607-bf8d9fe39f62.png)
![image](https://user-images.githubusercontent.com/26880226/42945693-4f0ea226-8b69-11e8-957d-5229466f637a.png)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2018-07-19 15:41 UTC, bdorney commented on ultraLatency.py
> +
keep this in alphabetical order.

2018-07-19 15:41 UTC, bdorney commented on ultraLatency.py
> +
Additionally the help menu needs to be updated to illustrate this is only relevant when calling with the `--internal` option.

2018-07-19 15:42 UTC, bdorney requested changes
Help menu does not illustrate that the added option is only effective when `--internal` is called.  Update.

2018-07-19 17:55 UTC, bdorney commented on ultraLatency.py
> +                      help="Channel on the VFATs on which to run the latency scan. This only applies when calling the --internal option; otherwise the default value is used.", metavar="chan", default
Change:

> otherwise the default value is used.

to:

> otherwise the OR of all channels is used.

2018-07-23 10:38 UTC, bdorney approved these changes

2018-07-27 09:50 UTC, jsturdy approved these changes

2018-08-14 12:33 UTC, merged