Fixed ultraThreshold, added options
cms-gem-daq-project/vfatqc-python-scripts pull request #68
Opened 2017-04-07 13:55 UTC by jsturdy

* Added some options
* Updated ultraThreshold
* updated run_scans
* some placeholders for future latency scans

2017-04-09 11:52 UTC, cbravo135 commented on run_scans.py
> +                         [options.config  for x in range(len(chamber_config))],
This last line of parameters shouldn't have a comma at the end

2017-04-09 11:53 UTC, cbravo135 commented on run_scans.py
> +      if trkdata:
We should also consider making a per channel trigger scan request impossible

2017-04-09 11:54 UTC, cbravo135 commented on qcoptions.py
> +parser.add_option("--scanmin", type="int", dest="scanmin",
I am not sure I am a fan of scanmin and scanmax being configurable, we should force the user to  scan over the whole range, and have a debug mode which does a shorter scan

2017-04-09 11:55 UTC, cbravo135 reviewed
We should maybe discuss a bit what you added, not sure we want it to be easy to not take full scans since this would break the analysis a bit. If we update here, it should be updated to not break the analysis at the same time.

2017-04-09 22:06 UTC, jsturdy commented on run_scans.py
> +                         [options.config  for x in range(len(chamber_config))],
Because python is awesome, this actually doesn't matter

2017-04-09 22:08 UTC, jsturdy commented on qcoptions.py
> +parser.add_option("--scanmin", type="int", dest="scanmin",
Depending on the scan type, you don't necessarily want to scan the same range, and having these parameters removes the worse practice of hard-coding values

2017-04-09 22:10 UTC, jsturdy commented on run_scans.py
> +      if trkdata:
Hmm, this was what I thought I had cleaned up, the logic currently goes:
```

    if perchannel:
      # do the per-channel scan setup
    else:
      # do the per VFAT scan setup, whether using tracking data or trigger data
```

2017-04-10 12:03 UTC, cbravo135 commented on run_scans.py
> +                         [options.config  for x in range(len(chamber_config))],
I figured you might care because it looks like are you really did here was clean up spacing.

2017-04-10 12:05 UTC, cbravo135 commented on ultraScurve.py
> +SCURVE_MIN = options.scanmin
Change these to be hardcoded to be the maximum range that works with the firmware so we don't have people not taking full scans.

2017-04-10 12:05 UTC, cbravo135 commented on ultraThreshold.py
> +THRESH_MIN = options.scanmin
These should also be hardcoded

2017-04-10 12:06 UTC, cbravo135 requested changes
The scan range of ultraScurve.py and ultraThreshold.py should be hardcoded

2017-04-20 09:20 UTC, cbravo135 approved these changes

2017-04-20 09:23 UTC, merged